### ISSUE TITLE
Where is the Privacy Policy?

### ISSUE THREAD

**Issue by richardmacduff** [immuni-app/immuni-documentation#69] opened 2020-05-25 15:50 UTC
A Privacy Policy is still missing from the documentation.
I understand that development is still ongoing, but if design has been settled upon, then there's nothing to keep you from releasing a comprehensive Privacy Policy.
Also, once the application is release, the Privacy Policy will be necessary to determine if and how the application Behaves As Advertised or not.

In short, code *does* things, and there will be enought discussion on how it does them.
The Privacy Policy tells us *what* the code should do, so I see the Privacy Policy as (one) essential tool in analysing your app.

Oh, by the way: a Privacy Policy is also a legal requirement.

Thank you
Walter Vannini

**Comment by pietro909** [comment] 2020-05-25 17:45
Isn't this a duplicate of https://github.com/immuni-app/immuni-documentation/issues/16 ?

**Comment by richardmacduff** [comment] 2020-05-26 10:03
Not really.
The Privacy Policy is a specific document, not some fleeting
privacy-related remarks that can be put anywhere in the documentation.
Thank you for allowing me to clarify.

Walter Vannini - GDPR Consultant & Auditor (ISDP10003)

Il lun 25 mag 2020, 19:45 pietro909 <notifications@github.com> ha scritto:

**Comment by Garolla** [comment] 2020-05-27 20:28
@richardmacduff Provocatory question from a common developer. Why don't you write it yourself and submit a pull request? Why we, are Italians, seems to pretend everything from Bending Spoons, for free, nonetheless?

**Comment by richardmacduff** [comment] 2020-05-31 15:38
> Provocatory question from a common developer. Why don't you write it yourself and submit a pull request? Why we, are Italians, seems to pretend everything from Bending Spoons, for free, nonetheless?

Bending Spoons _volunteered_ to develop a CoVid contact tracing app. 

The Privacy Policy is part and parcel of the development, is required by law, and is also one of the main documents to assess a data controlller's (that's eventually the Ministry, Bending Spoons being eventually a processor) compliance. Not exactly the kind of document that can or should be written by an outsider.

**Comment by saveveltri** [comment] 2020-06-03 09:13
dear @Garolla, 
could you elaborate on the concept of `Common Developer`? Also... In my honest opinion, the sentence 
> Why don't you write it yourself and submit a pull request? 

is much more provocatory than any polite and legitim criticism that has been submitted by @richardmacduff 

Also, as far as I know, our government has funded this project, so It's not correct to insinuate that there is someone who is asking for something for free.

**Comment by vi-enne** [comment] 2020-06-03 09:41
@richardmacduff 
Does this answer your question?
https://www.immuni.italia.it/app-pn.html

I am genuinely asking, since I am not an expert  :)

**Comment by richardmacduff** [comment] 2020-06-03 21:19
@vi-enne hi, and yes, thank you, it does. Now the question becomes "why aren't the privacy policy and (redacted) DPIA and Risk assessment not part of /Documentation or /Design?"
Unless, of course, we are subscribing to the idea that a software is nothing else but its code.
I see another issue asking precisely for such documentation to be put on github, rather than offline, we'll see. Also thank you for moral support above ;)
W

**Comment by immuniopensource** [comment] 2020-06-03 21:53
Thanks @richardmacduff for your contribution. As you mentioned this issue is solved so we are closing it for now. Let us now how can we further support you, thanks!

**Closed as completed by immuniopensource** 2020-06-03 21:53 UTC
Labels: triage
