### ISSUE TITLE
Offensive representation of women in one of the welcome screens

### ISSUE THREAD

**Issue by FraKenMas** [immuni-app/immuni-documentation#88] opened 2020-06-02 15:10 UTC
I would like to report that many of my friends, especially women, noticed how one of the drawings used in the welcome section of the app (precisely the third one in Welcome.png, see attachment) represents women in a stereotyped way.
The woman holds a baby and she's dressed in pink while, on the other side, there is a man working on his laptop dressed in blue. The problem that we've noticed is that the two representations, put side-by-side like in the image, tend to suggest two opposite (and outdated) situations and a very stereotyped color code.
Since the app will be downloaded nationwide and the italian government supports this initiative directly, I suggest to edit / remove / change the drawing in a way that the representation of women follows a more modern view of gender equality.

![Welcome](https://user-images.githubusercontent.com/56551009/83534751-885b9b80-a4f1-11ea-9409-73ee581de2ee.png)

**Comment by immuniopensource** [comment] 2020-06-02 16:20
Good evening @FraKenMas. We have received this feedback a few times and are already at work to update the images.
We regret and apologise for not having had the sensitivity to notice this during the design phase.
Expect this to be fixed with the next updates of the app and the website over the next couple of days. Thanks for your insightful feedback!

**Comment by gianvitofanelli** [comment] 2020-06-02 20:18
Hi everyone, thanks @FraKenMas for sharing this issue and thanks to @immuniopensource for acknowledging it.

I think it’s fine to remove this kind of subjects, as you are doing, and to make other illustrations genderless; or to have multiple versions that are shown random (e.g. the doctor and person illustrations in the home page of the app). By the way, I believe that making them genderless will work fine and it’s easier.

**Comment by Erenor** [comment] 2020-06-03 10:59
This is NOT a problem of gender equality.
This is a problem of gender interpretation.

You are assuming that the person with the pink shirt is a woman only because you cannot see anything else.
You are assuming that the "item" held is a baby only because you cannot see anything else.
You are assuming that the person in blue is the father only because you cannot see anything else.

In fact, the "pink" person could be either a man or a woman (or whatever other gender-fluid person we can think of).
The "baby" could be a doll or a real baby. Not necessarily that woman's child (babysitter? Sister? Whatever else?).
The person in blue could be a man, a woman (yes, women can have short hair), and there's nothing that suggests they are related in any way. 


This "issue" should be closed as "too short-sighted" to be a real issue.

**Comment by gianvitofanelli** [comment] 2020-06-03 11:02
Yes, of course it's a doll.

**Comment by devneri** [comment] 2020-06-03 11:20
Let's stop seeing sexism even where it's not there. It is normal for a mother to look after her baby. Or not? By the way the two people seem to be in different apartments. In another screenshot [In another screenshot](https://github.com/immuni-app/immuni-app-android/blob/master/app/src/main/res/drawable-hdpi/ic_onboarding_exposure.png) is there also a father taking a little girl for a walk? What do you do in this case? This is not an issue.

**Comment by gianvitofanelli** [comment] 2020-06-03 11:43
For whoever wants to elaborate on this topic
https://airbnb.design/your-face-here/

**Comment by FraKenMas** [comment] 2020-06-03 12:55
I do not think that the picture leaves much to interpretation. In a case like that the principle of Occam's razor is the correct one to apply: the solution of a problem is often the more simple one. The first thing that comes to my mind (and in that of my friends) is the one I described in OP. A woman holding a baby on the left and a man probably working on the right. I never said that the figure on the right is the father of the child nor he has any kind of relation with the figure on the left, as none of this is relevant.
Taken individually, the two figures are fine (like the one of the man hand in hand with a little girl) but, as I wrote in OP, the problem arises when the two representations are put side-by-side as to suggest two opposite situations. I support every gender and sexual identity, but I also support women's right to not to be depicted in this antiquated way.

I wrote this post also because many people close to me felt offended and I thought it was the right thing to give them voice and respecting their sensibility.

**Comment by GabrieleSammartino** [comment] 2020-06-03 13:19
A vo caga

**Comment by vfiore** [comment] 2020-06-03 13:52
Whatever. The usual insanity.

**Comment by dontyna** [comment] 2020-06-03 13:52
The problem is that the image of a woman taking care of a baby in the same picture while a man is working perpetuates a stereotype: men are part of the workforce, even during the lockdown, women are mothers who take care of children. And the more a stereotype is represented, especially in the public images and marketing features, the more behaviors will tend to adjust to them. I praise the developers to have taken care of the issue as it seems.

**Comment by vfiore** [comment] 2020-06-03 14:02
Yes, yes. And, for all we know, the guy may be goofing about or watching you-know-what. The beauty is in the eye of the ...beer-holder.

**Comment by Erenor** [comment] 2020-06-03 14:33
I understand the fact that, if someone has prejudices, they will be able to find "subliminal messages" everywhere. I wonder why nobody felt offended by the color of the skin, for example. Can't not-white (sorry for the definition, i hate these kind of terms) people work or have children? Where are the "disabled people" representatives? You see, this can be extended to almost any length. 

I must admit that the fact that a woman is holding a child and is about to feed him/her came to my mind, but it wasn't offensive (after all, men cannot feed children, right? At least for now, who knows what the future science will bring :-) ), since this is just a picture of what can happen in a family, and by no means it is intended for representing roles, otherwise there are a lot of them missing. 

The stereotype cannot be identified within a single image, because images represent a lot of different ideas and concepts. Looking at the other app's images, in fact, we see that surely they do not identify fixed roles in genders: starting from here, blindy judging a single image without getting more information on the app's images as a whole, means the observer is not objective, and thus this is not an issue with the app, but with the observer.

I hope my words are taken as they are: an opinion, an argumentation, not an offense or anything like that :-)

**Comment by vfiore** [comment] 2020-06-03 14:39
@Erenor, agree. It's the mindset of the professional grievancers.

**Comment by gionn** [comment] 2020-06-03 15:02
the images on https://www.immuni.italia.it/ has already been updated:

![Screenshot from 2020-06-03 17-01-31](https://user-images.githubusercontent.com/71768/83653301-e6ed4c00-a5bb-11ea-8e82-893325b89180.png)

**Comment by FraKenMas** [comment] 2020-06-03 15:07
@Erenor I understand your point, but the issue I've opened regards this single image that, as I said, offended many people. I agree that the design of the app could be more inclusive, but I think it's better to discuss elsewhere and I'll be glad to do so.
Yet I don't think that what we are talking about it's a prejudice. Simply we are so used to see women depicted in a certain way that we are desensitized. I repeat, the problem is not the fact that a woman holds a baby or a man is working on his laptop. This things are completely fine, it's the fact that the image arranges them in a way that seems to suggest the traditional way of thinking. It is up to the designer to create something that is as inclusive and respectful as possible (see the link provided by @gianvitofanelli ). In this image the designer failed to do so.
I'm a man and at first sight I didn't notice this problem I described. My girlfriend and some of my female friends pointed this out to me and I realized that each person is more sensible to different things. I understand their point and I support them in promoting more modern and inclusive ways of depicting them and their role in society.

**Comment by Aubreymcfato** [comment] 2020-06-03 15:07
Thanks for @immuniopensource for fixing this. As @FraKenMas tried to say, Immuni is a app that's strictly correlated with a lockdown that highlighted, _again_, how much women are taking the burden of family care. Of course that's the real problem, and not an image per se, but changing it is a little step in the right direction. I'm sure there was no malevolence from the start, but now it's better.

**Comment by fira** [comment] 2020-06-03 18:21
i'm very pained to have to point this out and normally wouldn't, but seeing the resolution, this is just too much, i'm sorry. 
from a purely logical or math standpoint, saying swapping the combination is "more equal" is actually directly implying that they are in themselves not equal to begin with... this is just screwed up on so many levels. this is only at most a forward step regarding stereotypes, and at worst actually fundamentally backwards.
i could go on about it, but i already went way out of my way by posting this and will just go cry in a corner instead of loitering this issue...

**Comment by ghost** [comment] 2020-06-03 21:36
> The problem is that the image of a woman taking care of a baby in the same picture while a man is working perpetuates a stereotype: men are part of the workforce, even during the lockdown, women are mothers who take care of children. And the more a stereotype is represented, especially in the public images and marketing features, the more behaviors will tend to adjust to them. I praise the developers to have taken care of the issue as it seems.

As a girl, as a developer, as a data scientist, I want to thank to you @dontyna , to @FraKenMas and to @immuniopensource as well to update this image. We are workers like you guys and we're so tired to be represented only as mothers or just women. I'm not a mother, just a girl, and now I need to take care of my notebook. 
Thanks to all of you guys.

**Comment by vfiore** [comment] 2020-06-04 08:10
OK, insanity for insanity, now I complain officially that as a working man I am offended by the new picture that unfairly characterizes me and my wife etc.etc. No, seriously. Or are some more equal than others in these orwellian times?

**Comment by Erenor** [comment] 2020-06-04 15:03
Well, the day when we will talk about "a person" and not "a man" or "a woman" will be the day when stereotypes will just stop to exist.
The people I work with are "collegues", not "men and women", to me. That's why i don't really care who is holding a baby and who is buying diapers on an ecommerce.

I have friends of any gender who just do what is needed at home, with their partners or alone, if the partner is doing something else. (side note: you see, no need to involve gender while talking about people, that's just irrelevant to me).

Equality is about thinking that anything is doable by anyone, regardless of gender, sexuality, religion, or whatever else. The only fact that could stop someone from doing something is their ability to do so: for example, i'm not able to pilot an airplane, because I never learnt. Not because I'm a woman or a man.

That's what I mean when I say that the "issue is the observer". 

I understand that many people view equality as "we are different, but we have to be treated the same way", but I always thought that such a sentence exacerbates the difference. I like to think "we are the same, no need to treat you differently".

**Comment by Alexmitter** [comment] 2020-06-15 09:07
There is no representation of drag, trans and non-binary minorities, this is unacceptable. Those people are also workers and/or mothers.

**Comment by immuniopensource** [comment] 2020-07-03 14:02
Hi @FraKenMas, since the original issue has been fixed I'm closing it for now. Thanks for your insightful feedback!

**Closed as completed by immuniopensource** 2020-07-03 14:02 UTC
Labels: enhancement, Frontend/App
