### ISSUE TITLE
Android Device Location permission (are you sure ?)

### ISSUE THREAD

**Issue by mciociola77** [immuni-app/immuni-documentation#19] opened 2020-05-15 09:54 UTC
> Location (Android only). On Android devices, Location needs to be on to detect nearby devices, although the A/G Framework’s documentation explicitly states that it does not actually use location data. This may be quite confusing for the user, but unfortunately it is outside of the Android App’s control. Please note that this does not mean that the Android App will request the Location permission, but only that Location needs to be activated at system level in order for the A/G Framework to work properly.
> 

This doesn't seem what Google is stating . And that can potentially kill the usage as we have 75% of Android in Italy. I would strongly recommend to verify and double check.

**Comment by vincenzoiovino** [comment] 2020-05-15 10:25
> > Location (Android only). On Android devices, Location needs to be on to detect nearby devices, although the A/G Framework’s documentation explicitly states that it does not actually use location data. This may be quite confusing for the user, but unfortunately it is outside of the Android App’s control. Please note that this does not mean that the Android App will request the Location permission, but only that Location needs to be activated at system level in order for the A/G Framework to work properly.
> 
> This doesn't seem what Google is stating . And that can potentially kill the usage as we have 75% of Android in Italy. I would strongly recommend to verify and double check.

So they are saying that the app does not use location but needs that location is active, right?
In this case, since location is active, many other apps can and will use location and drain the battery. 
Is it correct?
So any advantage of BLE seems lost.

**Comment by mciociola77** [comment] 2020-05-15 10:45
Dalla documentazione dell’A/G Framework emerge chiaramente in diversi punti che le applicazioni che utilizzano questo framework non dovranno/potranno accedere alla posizione dell’utente:
<img width="596" alt="IMMUNI_App_Feedback_-_Google_Docs" src="https://user-images.githubusercontent.com/65396454/82042254-e131d400-96a9-11ea-9e77-e16b9363ec6e.png">

**Comment by alexit84** [comment] 2020-05-15 12:35
Moreover, this differs from what stated on Google Exposure Notification docs: 
<img width="624" alt="Schermata 2020-05-15 alle 09 32 07" src="https://user-images.githubusercontent.com/3973382/82050828-172a8480-96b9-11ea-8166-510a630bb628.png">
https://blog.google/documents/68/Android_Exposure_Notification_API_documentation_v1.2.pdf

**Comment by sroddy** [comment] 2020-05-15 13:39
Due to how Android internally works, BLE scanning requires system-level Location Services to be enabled. Check this url for reference: https://issuetracker.google.com/issues/37065090

We have been in touch with the Google team working on the Exposure Notification framework, and have asked them about this very issue. They confirmed that there's a requirement that Location Services be enabled.

Please note that Location Services do not require to have any hardware sensor active (e.g. the GPS can be off).

Also note that the app itself won't be able to access the location of the device. In fact the permissions are not even included inside the AndroidManifest file (as it is also required per Google policy, like @alexit84 said). The Exposure Notification SDK will never surface any location-related data to the app.

**Comment by mciociola77** [comment] 2020-05-15 13:49
Thanks @sroddy 
does it means user will be asked this permission ?
Thanks 

![0_gPIWWOaBlVKFxx9i](https://user-images.githubusercontent.com/65396454/82057437-9e7cf580-96c3-11ea-9d7b-d4f750a4967d.png)

**Comment by mciociola77** [comment] 2020-05-15 14:21
Btw 
https://blog.google/documents/68/Android_Exposure_Notification_API_documentation_v1.2.pdf

**Bluetooth functionality, including all broadcast and scanning for BLE beacons and local database storage, happens within Google Play services on-device. Your app will need to have the BLUETOOTH permission in its manifest, but does not require ACCESS_FINE_LOCATION or BLUETOOTH_ADMIN.**

The thread you @sroddy are referring to https://issuetracker.google.com/issues/37065090
is from 2015 !

I would recommend to double check again cause what you're saying is not confirmed anywhere.

Thanks

**Comment by sroddy** [comment] 2020-05-15 14:25
The user will not see the popup you indicate. They will see an ad-hoc popup that is automatically displayed by the Exposure Notification SDK and was created by Google for just this specific purpose. I don't think we know what the message will be exactly yet—it's up to Google to decide.

**Comment by sroddy** [comment] 2020-05-15 14:52
@mciociola77 the thread is from 2015, the year in which Android 6.0 was released and introduced the specific requirement of having the Location Services active in order to perform BLE scanning. A requirement that no one, Google Play Services included, can bypass. As you can see from the (long) discussion, it's still active nowadays and somehow debated.

We have double-checked with the very team working on the Exposure Notification API at Google and they confirmed what we write in the documentation. As we write there, this is indeed suboptimal but we have no control over it. It's a Google decision.

In any case, following also the guidelines you reported above, Immuni won't include in its manifest ACCESS_FINE_LOCATION and will never use, nor have direct access to any location-related data.

**Comment by alexit84** [comment] 2020-05-15 15:22
Thank you for the clarification, @sroddy.
So if the there isn't the ACCESS_FINE_LOCATION on the manifest and no popup like the one showed by @mciociola77 will be displayed, in which way the app will need the location permission to work?

**Comment by GennAvi** [comment] 2020-05-15 15:41
Please push Google to make a proper public and detailed clarification about the need of having the Location service turned on. I think it is important if you really want people to opt-in

**Comment by vincenzoiovino** [comment] 2020-05-15 17:42
> @mciociola77 the thread is from 2015, the year in which Android 6.0 was released and introduced the specific requirement of having the Location Services active in order to perform BLE scanning. A requirement that no one, Google Play Services included, can bypass. As you can see from the (long) discussion, it's still active nowadays and somehow debated.
> 
> We have double-checked with the very team working on the Exposure Notification API at Google and they confirmed what we write in the documentation. As we write there, this is indeed suboptimal but we have no control over it. It's a Google decision.
> 
> In any case, following also the guidelines you reported above, Immuni won't include in its manifest ACCESS_FINE_LOCATION and will never use, nor have direct access to any location-related data.

Give a reference to this "double check". Your reference of 2015 seems to clash with what stated by Google in 2020. We cannot trust you on faith.

**Comment by iamareebjamal** [comment] 2020-05-16 08:08
@vincenzoiovino https://stackoverflow.com/questions/33045581/location-needs-to-be-enabled-for-bluetooth-low-energy-scanning-on-android-6-0

**Comment by vincenzoiovino** [comment] 2020-05-16 11:15
> @mciociola77 the thread is from 2015, the year in which Android 6.0 was released and introduced the specific requirement of having the Location Services active in order to perform BLE scanning. A requirement that no one, Google Play Services included, can bypass. As you can see from the (long) discussion, it's still active nowadays and somehow debated.
> 
> We have double-checked with the very team working on the Exposure Notification API at Google and they confirmed what we write in the documentation. As we write there, this is indeed suboptimal but we have no control over it. It's a Google decision.
> 
> In any case, following also the guidelines you reported above, Immuni won't include in its manifest ACCESS_FINE_LOCATION and will never use, nor have direct access to any location-related data.

You do not use ACCESS_FINE_LOCATION but do you require ACCESS_COARSE_LOCATION ?
That is, do you include permission for Network Provider, or not?
Can you confirm or deny that?

**Comment by lorenzoranucci** [comment] 2020-05-16 14:48
> It's not really a bug - if a malicious app developer can scan for known Bluetooth beacons, then they can figure out your location without raising the user's suspicions by asking for location permissions. So asking for BLE access must unfortunately be treated the same as asking for your rough location.

I found [here](https://stackoverflow.com/questions/33045581/location-needs-to-be-enabled-for-bluetooth-low-energy-scanning-on-android-6-0) this interesting consideration. I hope it can help to explain to people why this permission is required.

**Comment by vincenzoiovino** [comment] 2020-05-16 21:09
> > It's not really a bug - if a malicious app developer can scan for known Bluetooth beacons, then they can figure out your location without raising the user's suspicions by asking for location permissions. So asking for BLE access must unfortunately be treated the same as asking for your rough location.
> 
> I found [here](https://stackoverflow.com/questions/33045581/location-needs-to-be-enabled-for-bluetooth-low-energy-scanning-on-android-6-0) this interesting consideration. I hope it can help to explain to people why this permission is required.

So it seems that at least ACCESS_COARSE_LOCATION (network provider data) is required?

But notice that In the thread you mention a user also affirms that:
 "But on some devices is also necessary your phone location service (GPS) to be switched on, so you can discover peripheral devices. I found that using Nexus 5x, with Android 7.0."

So, on SOME phones, for Immuni to work GPS has to be activated and other apps can drain the battery? So all the advantages of BLE are lost.

**Comment by cascafico** [comment] 2020-06-04 08:34
Just tried on Android 6.0.

Immuni doens't accept "wifi - mobile network" as localization service (which I suppose is related to ACCESS_COARSE_LOCATION). The sole method is enabling GPS, so getting  the usual higher battery drain.

**Comment by immuniopensource** [comment] 2020-08-14 09:08
As the concerns have already been addressed by @sroddy throughout the thread, we're closing this issue for now. For any other inquiry please open a new dedicated issue. Thank you!

**Closed as completed by immuniopensource** 2020-08-14 09:08 UTC
Labels: triage
